export const HELP_MAP: Record<string, string> = {
  help: "/help [command]",
  status: "/status",
  clear: "/clear",
  exit: "/exit",
  whoami: "/whoami",
  plan: "/plan (enter plan mode) | /plan from @file | /plan status | /plan diff | /plan approve (latest) | /plan exit",
  start: "/start [--task <task_id>]",
  run: "/run status | /run pause | /run resume | /run cancel",
  tasks: "/tasks",
  attach: "/attach <run_id>",
  context:
    "/context show | /context expand|trim [--max-lines N --max-files N --depth N --topk N] [--include docs|tests] [--drop docs|tests] [--keep paths=...] [--hydrate] | /context rebuild",
  pins: "/pins add @<file> | /pins rm @<file> | /pins list | /pins clear",
  verify: "/verify [--target <path|package>] [--strict]",
  fix: "/fix",
  diff: "/diff",
  apply: "/apply",
  usage: "/usage month | /usage today",
  export: "/export ledger",
  invoice: "/invoice preview",
  cost: "/cost explain <task_id|run_id>",
  lane: "/lane set speed|balanced|quality|cost-saver",
  risk: "/risk set low|standard|high",
  budget: "/budget cap <usd> | /budget status",
  permissions: "/permissions [allow|ask|deny] \"<cmd>\"",
  doctor: "/doctor",
  logs: "/logs tail [--run <id>]",
  project: "/project status | /project connect",
  pr: "/pr status",
  init: "/init [--portable] [--refresh]",
  next: "/next"
};

export function getHelpLines(): string[] {
  return [
    "/help",
    "/help <command>",
    "/status",
    "/clear",
    "/exit",
    "/whoami",
    "/plan [from @file]",
    "/plan status",
    "/plan diff",
    "/plan approve (approves latest plan)",
    "/plan exit",
    "/start",
    "/start --task <task_id>",
    "/next",
    "/run status",
    "/run pause|resume|cancel",
    "/tasks",
    "/attach <run_id>",
    "/context show",
    "/context expand|trim",
    "/context rebuild",
    "/pins add|rm|list|clear",
    "/verify",
    "/verify --target <path|package>",
    "/verify --strict",
    "/fix",
    "/diff",
    "/apply",
    "/usage month",
    "/usage today",
    "/invoice preview",
    "/cost explain <task_id|run_id>",
    "/lane set <speed|balanced|quality|cost-saver>",
    "/risk set <low|standard|high>",
    "/budget cap <usd>",
    "/budget status",
    "/permissions",
    "/doctor",
    "/logs tail",
    "/export ledger",
    "/project status",
    "/project connect",
    "/pr status",
    "/init"
  ];
}
